# Generated by Django 3.2.2 on 2021-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0004_alter_userpreference_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('GBP', 'GBP')], max_length=300, null=True),
        ),
    ]
